// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdWbM1vy_YjYOEqOpRpQuV4gKo0HOQ-Fo',
    appId: '1:200474843670:web:dfd9bc06ad2cba50923337',
    messagingSenderId: '200474843670',
    projectId: 'testapp-9bb40',
    authDomain: 'testapp-9bb40.firebaseapp.com',
    storageBucket: 'testapp-9bb40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Z7kYeCAtibfMdRJAQMT0qAv4-CV_sik',
    appId: '1:200474843670:android:1d3197a76bbd24fb923337',
    messagingSenderId: '200474843670',
    projectId: 'testapp-9bb40',
    storageBucket: 'testapp-9bb40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLXSoKvQm-WPp51neAXe9QvHV8yL03Yxg',
    appId: '1:200474843670:ios:2a1674402680327a923337',
    messagingSenderId: '200474843670',
    projectId: 'testapp-9bb40',
    storageBucket: 'testapp-9bb40.appspot.com',
    iosBundleId: 'com.example.lookodu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLXSoKvQm-WPp51neAXe9QvHV8yL03Yxg',
    appId: '1:200474843670:ios:b4df8cedc71d6cb9923337',
    messagingSenderId: '200474843670',
    projectId: 'testapp-9bb40',
    storageBucket: 'testapp-9bb40.appspot.com',
    iosBundleId: 'com.example.lookodu.RunnerTests',
  );
}
